const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Bullet,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.EightDir,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Behaviors.Pin,
		C3.Behaviors.Tween,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Bullet: 0},
	{TiledBackground: 0},
	{Solid: 0},
	{Sprite2: 0},
	{Sprite: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{"8Direction": 0},
	{mcgonagall: 0},
	{Keyboard: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{mcgonagal: 0},
	{score: 0},
	{GameOverText: 0},
	{BtnRestart: 0},
	{Touch: 0},
	{Pin: 0},
	{Hitbox: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{judul: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Tween: 0},
	{Btnstart: 0},
	{win: 0},
	{Audio: 0},
	{Sprite14: 0},
	{Sprite21: 0},
	{Text: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Timer: 0},
	{Score: 0},
	{Gameover: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	mcgonagall: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	mcgonagal: class extends self.ISpriteInstance {},
	score: class extends self.ITextInstance {},
	GameOverText: class extends self.ISpriteInstance {},
	BtnRestart: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Hitbox: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	judul: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Btnstart: class extends self.ISpriteInstance {},
	win: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {}
}